/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    login: [];
    authenticate: [];
    dashboard: [];
    'store.task': [];
    'update.task': [
      {
        name: 'task';
        required: true;
        binding: 'id';
      },
    ];
    'delete.task': [
      {
        name: 'task';
        required: true;
      },
    ];
    'storage.local': [
      {
        name: 'path';
        required: true;
      },
    ];
  }
}
export {};
